### ISSUE TITLE
MediaPipe vs OpenCV

### ISSUE THREAD

**Issue by IgnacioPardo** [Defeeeee/FormAI#1]
Investiguen Google MediaPipe para el Body Tracking, trackea poses mas específicas que los de OpenCV.

https://ai.google.dev/edge/mediapipe/solutions/studio
https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker

![image](https://github.com/user-attachments/assets/e22f5cc4-734c-4ea8-a37f-9ecb24696f0d)

**Comment by Defeeeee** [comment]
Dale, lo investigamos. Gracias por el aporte chona

**Comment by Defeeeee** [comment]
Decidimos utilizar mediapipe
